import Image from "next/image";
import { ArrowDown, ArrowUpRight, CheckCircle2, Download, MapPin } from "lucide-react";
import { ExternalLink, Nav } from "@/components/site";
import { ContactSection } from "@/components/contact";
import { ProjectShowcase } from "@/components/projects";
import { experience } from "@/data/experience";
import { profile } from "@/data/profile";
import { skills } from "@/data/skills";

const learning = ["Linux & networking foundations", "Git & source-control workflows", "Docker & containerization", "Jenkins & GitHub Actions", "AWS infrastructure", "Kubernetes & Amazon EKS", "Helm & deployment strategies", "Terraform & Infrastructure as Code", "Monitoring, logging & reliability", "Future focus: DevSecOps, observability & platform engineering"];
const principles = [["Understand the problem", "Translate product, user and business requirements into a clear engineering plan."], ["Build for maintainability", "Prefer reusable components, readable code, modular architecture and documented decisions."], ["Automate repeatable work", "Use CI/CD pipelines, containers and infrastructure automation to reduce manual deployment effort."], ["Operate what is built", "Use logs, monitoring, health checks and root-cause analysis to improve reliability."]];

export default function Home() {
  const person = { "@context": "https://schema.org", "@type": "Person", name: profile.name, jobTitle: "Senior Full-Stack Engineer", url: "https://sairamraavi.github.io", sameAs: [profile.github, profile.linkedin] };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(person) }} /><a className="skip" href="#main">Skip to content</a><Nav />
    <main id="main">
      <section id="top" className="hero section"><div className="hero-copy"><p className="eyebrow">Senior Software Engineer <i /> Full-Stack <i /> Cloud & DevOps</p><h1>I build reliable digital products and the systems that deliver them.</h1><p className="lede">{profile.summary}</p><div className="button-row"><a className="button primary" href="#projects">View selected work <ArrowDown size={17} /></a><a className="button" href="/resume/sairam-raavi-resume.pdf" download><Download size={17} /> Download résumé</a></div><div className="hero-meta"><span><MapPin size={16} />{profile.location}</span><span>{profile.role}</span><span>Open to senior full-stack and DevOps-focused opportunities</span></div></div><div className="portrait-wrap"><Image src="/images/sairam-profile.jpeg" alt="Sairam Raavi" width={700} height={900} priority /><div className="portrait-note">Enterprise app engineering<br /><b>7+ years</b></div></div></section>
      <section id="about" className="section summary"><div className="section-label">01 / Foundation</div><div><h2>Engineering across applications, platforms and delivery.</h2><p>My professional foundation is enterprise application work: translating product and Figma requirements into dependable interfaces, integrating APIs, and maintaining Drupal, PHP, Angular and .NET systems. Alongside releases and production troubleshooting, I’m applying that experience to cloud infrastructure and delivery automation.</p><div className="metrics"><span><b>7+</b> years in software engineering</span><span><b>Full stack</b> frontend, backend & CMS</span><span><b>Applied labs</b> CI/CD & cloud automation</span></div></div></section>
      <section id="experience" className="section"><div className="section-label">02 / Experience</div><div className="timeline">{experience.map(item => <article className="timeline-item" key={item.role}><div><p className="eyebrow">{item.dates}</p><h2>{item.role}</h2><p className="muted">{item.company} · {item.location}</p></div><ul>{item.bullets.map(b => <li key={b}>{b}</li>)}</ul></article>)}</div></section>
      <section id="expertise" className="section"><div className="section-label">03 / Expertise</div><div><h2>Capabilities grounded in delivery.</h2><div className="skill-grid">{skills.map(([title, desc, list]) => <article className="skill" key={title}><h3>{title}</h3><p>{desc}</p><small>{list}</small></article>)}</div></div></section>
      <section id="projects" className="section"><div className="section-label">04 / Selected work</div><div><h2>Hands-on systems work, clearly scoped.</h2><p className="section-intro">Projects below are personal engineering work and learning labs—not commercial production claims.</p><ProjectShowcase /></div></section>
      <section id="learning" className="section learning"><div className="section-label">05 / Learning journey</div><div><h2>Continuous learning, applied through real systems.</h2><p>Practical engineering-lab work extending from full-stack development into cloud and platform delivery.</p><ol>{learning.map((item, i) => <li key={item}><span>{String(i + 1).padStart(2, "0")}</span>{item}</li>)}</ol><p className="learning-note">Applied topics include Docker multi-stage builds, Flask and Node.js containerization, AWS EC2/ECR/S3/IAM, EKS, Helm, CSI drivers, Lambda automation, EventBridge, CloudWatch and Terraform.</p></div></section>
      <section className="section approach"><div className="section-label">06 / Approach</div><div><h2>How I approach engineering work.</h2><div className="principles">{principles.map(([title, copy]) => <article key={title}><CheckCircle2 size={19} /><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
      <section id="blog" className="section blog-preview"><div className="section-label">07 / Writing</div><div><h2>Notes from the learning path.</h2><p className="section-intro">Drafts in progress—written to document systems work as it evolves.</p><div className="project-grid">{["From Full-Stack Development to DevOps: My Learning Roadmap", "Building a Jenkins CI/CD Pipeline for Flask on AWS", "Deploying a Containerized MERN Application to Amazon EKS"].map((title, i) => <article className="project-card" key={title}><p className="eyebrow">{["Career", "CI/CD", "Kubernetes"][i]} · Coming soon</p><h3>{title}</h3><p>Draft article documenting practical learning, tradeoffs and implementation notes.</p><a className="text-link" href="/blog/">Browse drafts <ArrowUpRight size={16} /></a></article>)}</div></div></section>
      <section className="section github"><div className="section-label">08 / Open source</div><div><h2>Build notes live on GitHub.</h2><p>Explore project repositories spanning Docker, Jenkins, AWS, Kubernetes, Terraform and full-stack service patterns.</p><ExternalLink href={profile.github}>View all repositories</ExternalLink></div></section>
      <section className="section education"><div className="section-label">09 / Education & credentials</div><div className="credential"><div><p className="eyebrow">Education</p><h2>B.Tech in Electronics & Communication Engineering</h2><p>NRI Institute of Technology · Graduated 2016</p></div><div><p className="eyebrow">Credentials</p><p><b>DevOps learning program</b> — In progress</p><p>Future AWS and Kubernetes certifications — Planned</p></div></div></section>
      <ContactSection />
    </main><footer><div><b>{profile.name}</b><span>Senior Full-Stack Engineer</span></div><div><a href="/blog/">Blog</a><a href="/resume/sairam-raavi-resume.pdf">Résumé</a><a href={profile.github}>GitHub</a><a href={`mailto:${profile.email}`}>Email</a></div><p>© {new Date().getFullYear()} · Designed and engineered with Next.js and TypeScript</p></footer>
  </>;
}
