"use client";
import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Github, Linkedin, Mail, Menu, Moon, Sun, X } from "lucide-react";
import { profile } from "@/data/profile";

const links = [["About", "#about"], ["Experience", "#experience"], ["Expertise", "#expertise"], ["Projects", "#projects"], ["Learning", "#learning"], ["Blog", "/blog/"], ["Contact", "#contact"]];
export function Nav() { const [open, setOpen] = useState(false); const [dark, setDark] = useState(true); const [active, setActive] = useState("#about"); const menuRef = useRef<HTMLElement>(null); useEffect(() => { const saved = localStorage.getItem("theme"); const d = saved ? saved === "dark" : window.matchMedia("(prefers-color-scheme: dark)").matches; setDark(d); document.documentElement.dataset.theme = d ? "dark" : "light"; const observer = new IntersectionObserver((entries) => entries.forEach(entry => { if (entry.isIntersecting) setActive(`#${entry.target.id}`); }), { rootMargin: "-42% 0px -52% 0px" }); links.filter(([, href]) => href.startsWith("#")).forEach(([, href]) => { const section = document.querySelector(href); if (section) observer.observe(section); }); return () => observer.disconnect(); }, []); useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); if (event.key === "Tab" && open && menuRef.current) { const items = menuRef.current.querySelectorAll<HTMLAnchorElement>("a"); if (!items.length) return; const first = items[0], last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [open]); const toggle = () => { const d = !dark; setDark(d); localStorage.setItem("theme", d ? "dark" : "light"); document.documentElement.dataset.theme = d ? "dark" : "light"; }; const navLinks = (mobile = false) => links.map(([n,h]) => <a aria-current={h === active ? "page" : undefined} className={h === active ? "active" : ""} href={h} key={n} onClick={() => mobile && setOpen(false)}>{n}</a>); return <header className="nav"><a className="brand" href="#top">SR<span>.</span></a><nav className="desktop" aria-label="Primary navigation">{navLinks()}</nav><div className="nav-actions"><button className="icon-button" aria-label="Toggle color theme" onClick={toggle}>{dark ? <Sun size={18}/> : <Moon size={18}/>}</button><a className="resume small" href="/resume/sairam-raavi-resume.pdf" download>Résumé</a><button className="menu icon-button" aria-label={open ? "Close navigation menu" : "Open navigation menu"} aria-expanded={open} aria-controls="mobile-menu" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div><AnimatePresence>{open && <motion.nav ref={menuRef} id="mobile-menu" className="mobile-menu" aria-label="Mobile navigation" initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}}>{navLinks(true)}</motion.nav>}</AnimatePresence></header> }
export function ContactIcons() { return <div className="contact-icons"><a aria-label="GitHub" href={profile.github}><Github size={19}/></a><a aria-label="LinkedIn" href={profile.linkedin}><Linkedin size={19}/></a><a aria-label="Send an email" href={`mailto:${profile.email}`}><Mail size={19}/></a></div> }
export function ExternalLink({href, children}:{href:string;children:React.ReactNode}) { return <a className="text-link" href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={16}/></a> }
